### PR TITLE
chore: some changes for JFF interop

### PR DESCRIPTION
**Pull request by TimoGlastra**
Have been tinkering a bit to get interop with MATTR launchpad.

It  now seems to get stuck on the presentation definition validation, so will have to look at the PEX library for that.

Not sure if the JWT verification bypass is 'ok'. If there's no JWT I think it would be fine to just not validate it, but if there is one, it is validated.

Not ready to be merged, but if you do take a look, maybe these changes can  be of help for getting the sphereon wallet working...

### CODE REVIEW

**Review by nklomp — COMMENTED** [review]
Cool, I was going to work on this tomorrow

Be aware that at some points we might need to include some logic for version discovery. Because basically `direct_post` is replacing `post` from versions < 17. In the old `post` mode, redirect_uri was required to be present, whilst now it can also have the response_uri, but not both.

**Comment by TimoGlastra** [comment]
Awesome thanks! I wasn't aware that it replaces post. More version logic... 😅

**Comment by nklomp** [comment]
Yeah, long live evolving specs. I cannot wait once things settle down to start refactoring and remove a lot of the complexities from handling multiple versions..

BTW be aware that some changes have been made to this lib, mainly bugfixes

**Comment by TimoGlastra** [comment]
Got it working with this very hacky encoding logic. Not sure how you're on adding dependencies, but with `qs` it's a one liner :) 

https://www.npmjs.com/package/qs?activeTab=dependencies

**Comment by nklomp** [comment]
FYI: I am taking some of the changes from this PR in the branch I am working on for V18 support

**Comment by TimoGlastra** [comment]
Yes, I was figuring that it's easiest if I push my 'hacks' and you can properly integrate it where needed. It's quite a mess in how I got things working :/

**Pull request closed without merging**
